language: python
python:
  - 3.6.3

install:
  - pip install -r requirements.txt
  - nvm install stable
  - npm install -g eslint-cli
  - npm install

services:
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE DATABASE travis_db;" -U postgres

script:
  - eslint --config .eslintrc.js eventually/static/src/
  - npm run build
  - cd eventually/
  - sudo touch /var/log/eventually.log
  - sudo chown -R $USER:$USER /var/log/eventually.log
  - pylint --rcfile=.pylintrc *
  - coverage run manage.py test

after_success:
  - coveralls
