# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0002_add_one_to_one_relation_to_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
