# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_added_relations_to_owner_and_to_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('goal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentors', models.ManyToManyField(related_name='mentors', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team.Team')),
            ],
        ),
    ]
