# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 23:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_added_relations_to_owner_and_to_members'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='teams',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=8),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
