# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_curriculum_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='team',
        ),
    ]
