# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_add_foreing_key'),
        ('authentication', '0001_initial'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='members',
            field=models.ManyToManyField(to='authentication.CustomUser'),
        ),
        migrations.AddField(
            model_name='vote',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(0, 'One'), (1, 'Multi')]),
        ),
    ]
