# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('parent_id', models.IntegerField(blank=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_id', models.IntegerField(blank=True)),
                ('task_id', models.IntegerField(blank=True)),
                ('vote_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
