# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_added_relations_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
