# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_type',
            field=models.IntegerField(choices=[(0, 'ToDo'), (1, 'In Progress'), (2, 'Done')], default=0),
        ),
    ]
