# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171027_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status_type',
            new_name='status',
        ),
    ]
