# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=20, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=20, verbose_name='second_name')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email_address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
