# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('second_name', models.CharField(max_length=20, verbose_name='second name')),
                ('middle_name', models.CharField(max_length=20, verbose_name='middle name')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2017, 10, 26, 22, 21, 23, 114151))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
