# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
