# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 8, 5, 51, 512986)),
        ),
    ]
