# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestedtopics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedtopics',
            old_name='title',
            new_name='name',
        ),
    ]
