# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='grade',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='statement',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
