# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20180531_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.BooleanField(default=False),
        ),
    ]
