# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='statement',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
